--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.597.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/4/2022 8:15:40 PM
-- Server version: 10.4.22
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE library;

--
-- Drop table `account`
--
DROP TABLE IF EXISTS account;

--
-- Drop table `book`
--
DROP TABLE IF EXISTS book;

--
-- Drop table `category`
--
DROP TABLE IF EXISTS category;

--
-- Drop table `library_card`
--
DROP TABLE IF EXISTS library_card;

--
-- Drop table `menu`
--
DROP TABLE IF EXISTS menu;

--
-- Drop table `notification`
--
DROP TABLE IF EXISTS notification;

--
-- Drop table `post`
--
DROP TABLE IF EXISTS post;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE library;

--
-- Create table `user`
--
CREATE TABLE user (
  id CHAR(36) NOT NULL DEFAULT '',
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(100) DEFAULT NULL,
  bar_code VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  created_date TIMESTAMP NULL DEFAULT current_timestamp,
  created_by VARCHAR(255) DEFAULT NULL,
  modified_date TIMESTAMP NULL DEFAULT current_timestamp,
  modified_by VARCHAR(255) DEFAULT NULL,
  is_deleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `post`
--
CREATE TABLE post (
  PostID CHAR(36) NOT NULL DEFAULT 'UUID',
  Title VARCHAR(255) DEFAULT NULL,
  Slug VARCHAR(255) DEFAULT NULL,
  Description TEXT DEFAULT NULL,
  Content LONGTEXT DEFAULT NULL,
  Image TEXT DEFAULT NULL,
  ViewCount INT(11) DEFAULT NULL,
  Type INT(11) DEFAULT NULL,
  CreatedDate TIMESTAMP NULL DEFAULT current_timestamp,
  CreatedBy VARCHAR(255) DEFAULT NULL,
  ModifiedDate TIMESTAMP NULL DEFAULT current_timestamp,
  ModifiedBy VARCHAR(255) DEFAULT NULL,
  Status BIT(1) DEFAULT b'1',
  IsDeleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (PostID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 862,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `notification`
--
CREATE TABLE notification (
  id CHAR(36) NOT NULL DEFAULT '',
  content VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `from` CHAR(36) DEFAULT NULL,
  `to` CHAR(36) DEFAULT NULL,
  to_email VARCHAR(255) DEFAULT NULL,
  is_readed BIT(1) DEFAULT b'1',
  created_date TIMESTAMP NULL DEFAULT current_timestamp,
  created_by VARCHAR(255) DEFAULT NULL,
  modified_date TIMESTAMP NULL DEFAULT current_timestamp,
  modified_by VARCHAR(255) DEFAULT NULL,
  is_deleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `menu`
--
CREATE TABLE menu (
  MenuID CHAR(36) NOT NULL DEFAULT 'UUID',
  Title VARCHAR(255) DEFAULT NULL,
  Slug VARCHAR(255) DEFAULT NULL,
  ParentID CHAR(36) DEFAULT '00000000-0000-0000-0000-000000000000',
  IsShowHome BIT(1) DEFAULT b'1',
  Link TEXT DEFAULT NULL,
  DisplayOrder INT(11) DEFAULT NULL,
  Type INT(11) DEFAULT NULL,
  CreatedDate TIMESTAMP NULL DEFAULT current_timestamp,
  CreatedBy VARCHAR(255) DEFAULT NULL,
  ModifiedDate TIMESTAMP NULL DEFAULT current_timestamp,
  ModifiedBy VARCHAR(255) DEFAULT NULL,
  Status BIT(1) DEFAULT b'1',
  IsDeleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (MenuID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `library_card`
--
CREATE TABLE library_card (
  id CHAR(36) NOT NULL DEFAULT '',
  card_number VARCHAR(50) NOT NULL,
  bar_code VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  active BIT(1) DEFAULT NULL,
  created_date TIMESTAMP NULL DEFAULT current_timestamp,
  created_by VARCHAR(255) DEFAULT NULL,
  modified_date TIMESTAMP NULL DEFAULT current_timestamp,
  modified_by VARCHAR(255) DEFAULT NULL,
  is_deleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `category`
--
CREATE TABLE category (
  id CHAR(36) NOT NULL DEFAULT '',
  name VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  meta_title VARCHAR(255) DEFAULT NULL,
  parent_id CHAR(36) DEFAULT NULL,
  show_on_home BIT(1) DEFAULT b'1',
  created_date TIMESTAMP NULL DEFAULT current_timestamp,
  created_by VARCHAR(255) DEFAULT NULL,
  modified_date TIMESTAMP NULL DEFAULT current_timestamp,
  modified_by VARCHAR(255) DEFAULT NULL,
  is_deleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `book`
--
CREATE TABLE book (
  id CHAR(36) NOT NULL DEFAULT '',
  book_code CHAR(20) DEFAULT NULL,
  book_name VARCHAR(255) DEFAULT NULL,
  publisher VARCHAR(100) DEFAULT NULL,
  author VARCHAR(100) DEFAULT NULL,
  language_code CHAR(10) DEFAULT NULL,
  price DECIMAL(15, 2) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  book_format INT(11) DEFAULT NULL,
  due_date TIMESTAMP NULL DEFAULT NULL,
  borrowed_date TIMESTAMP NULL DEFAULT NULL,
  date_of_purchase VARCHAR(255) DEFAULT NULL,
  isReferenceOnly BIT(1) DEFAULT b'0',
  image TEXT DEFAULT NULL,
  catalog_id CHAR(36) DEFAULT NULL,
  created_date TIMESTAMP NULL DEFAULT current_timestamp,
  created_by VARCHAR(255) DEFAULT NULL,
  modified_date TIMESTAMP NULL DEFAULT current_timestamp,
  modified_by VARCHAR(255) DEFAULT NULL,
  status BIT(1) DEFAULT b'0',
  is_deleted BIT(1) DEFAULT b'0'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `account`
--
CREATE TABLE account (
  id CHAR(36) NOT NULL DEFAULT '',
  user_name VARCHAR(255) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  full_name VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT '',
  avatar TEXT DEFAULT NULL,
  created_date TIMESTAMP NULL DEFAULT current_timestamp,
  created_by VARCHAR(255) DEFAULT NULL,
  modified_date TIMESTAMP NULL DEFAULT current_timestamp,
  modified_by VARCHAR(255) DEFAULT NULL,
  status INT(11) DEFAULT NULL,
  is_deleted BIT(1) DEFAULT b'0',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table user
--
-- Table library.user does not contain any data (it is empty)

-- 
-- Dumping data for table post
--
INSERT INTO post VALUES
('0fec1f8f-6195-460c-9dc2-974c42961892', 'tieu de mac dinh 2232334', 'tieu-de-mac-dinh-2232334', 'mo ta mac dinh', '"Type some text..."', '1649144309455_image', 200, 1, '2022-04-05 12:32:09', 'DOVANHAI', '2022-04-05 14:59:46', 'DOVANHAI', True, False),
('43ec1ee5-3c4b-4a4d-a910-86a6c1e37f1b', 'Tiêu đề bài đăng mặc định2222', 'tieu-de-bai-dang-mac-dinh2222', 'Mô tả mặc định', '"Type some text..."', '1649144245727_image', 200, 1, '2022-04-05 14:37:25', 'DOVANHAI', '2022-04-05 14:37:25', 'DOVANHAI', False, False),
('491e159f-838e-4503-b5db-b55aefe84d48', 'Tiêu đề bài đăng mặc định Tiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc địnhTiêu đề bài đăng mặc định', 'tieu-de-bai-dang-mac-dinh-tieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinhtieu-de-bai-dang-mac-dinh', 'Mô tả mặc định', '"Type some text..."', '1649150482734_image', 200, 1, '2022-04-05 16:21:22', 'DOVANHAI', '2022-04-05 16:21:22', 'DOVANHAI', True, False),
('57848cb0-994c-4a77-ae6c-4a847cf8e13c', 'Tiêu đề bài đăng mặc định 122', 'tieu-de-bai-dang-mac-dinh-122', 'Mô tả mặc định', '"Type some text..."', '1649144291792_image', 200, 1, '2022-04-05 12:24:08', 'DOVANHAI', '2022-04-05 14:59:41', 'DOVANHAI', True, False),
('5ae0af3b-37b8-45ee-9aaf-e99161fd0617', 'Tiêu đề bài đăng mặc định1111', 'tieu-de-bai-dang-mac-dinh1111', 'Mô tả mặc định', '"Type some text..."', '1649144230376_image', 200, 1, '2022-04-05 14:37:10', 'DOVANHAI', '2022-04-05 14:49:44', 'DOVANHAI', True, False),
('e5169eca-eab1-40df-b601-bfb0df5eb013', 'Tiêu đề bài đăng mặc định22', 'tieu-de-bai-dang-mac-dinh22', 'Mô tả mặc định', '"Type some text..."', '1649143885600_image', 200, 1, '2022-04-05 14:31:25', 'DOVANHAI', '2022-04-05 14:31:25', 'DOVANHAI', True, True);

-- 
-- Dumping data for table notification
--
-- Table library.notification does not contain any data (it is empty)

-- 
-- Dumping data for table menu
--
-- Table library.menu does not contain any data (it is empty)

-- 
-- Dumping data for table library_card
--
-- Table library.library_card does not contain any data (it is empty)

-- 
-- Dumping data for table category
--
-- Table library.category does not contain any data (it is empty)

-- 
-- Dumping data for table book
--
-- Table library.book does not contain any data (it is empty)

-- 
-- Dumping data for table account
--
-- Table library.account does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;